### PR TITLE
Avoid Undefined offset: 0 error by testing if the element exists before accessing it

### PR DESCRIPTION
**Pull request by tcitworld**
```json
{
  "reqId": "YqVbQXz6WFiKbxaTMqzD",
  "level": 3,
  "time": "2022-07-27T08:52:24+02:00",
  "remoteAddr": "",
  "user": "--",
  "app": "PHP",
  "method": "",
  "url": "--",
  "message": "Undefined offset: 0 at /var/www/nextcloud/apps/contacts/lib/Service/SocialApiService.php#186",
  "userAgent": "--",
  "version": "24.0.3.2",
  "exception": {
    "Exception": "Error",
    "Message": "Undefined offset: 0 at /var/www/nextcloud/apps/contacts/lib/Service/SocialApiService.php#186",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/contacts/lib/Service/SocialApiService.php",
        "line": 186,
        "function": "onError",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/apps/contacts/lib/Service/SocialApiService.php",
        "line": 413,
        "function": "updateContact",
        "class": "OCA\\Contacts\\Service\\SocialApiService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/contacts/lib/Cron/SocialUpdate.php",
        "line": 66,
        "function": "updateAddressbooks",
        "class": "OCA\\Contacts\\Service\\SocialApiService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/Job.php",
        "line": 79,
        "function": "run",
        "class": "OCA\\Contacts\\Cron\\SocialUpdate",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php",
        "line": 47,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/cron.php",
        "line": 151,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\QueuedJob",
        "type": "->"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/Log/ErrorHandler.php",
    "Line": 92,
    "CustomMessage": "--"
  }
}
```

### CODE REVIEW

**Review by miaulalala — APPROVED** [review]
lgtm

**Review by ChristophWurst — APPROVED** [review]
Please rebase

**Comment by tcitworld** [comment]
Rebased (and fixed)

**Pull request merged**
