### PR TITLE
fix: validate group name

### PR DESCRIPTION
**Pull request by Dominik-Kuzila**
Added a validator to addGroup action so that a new group name cannot be an empty string.
#2367

### CODE REVIEW

**Comment by SebastianKrupinski** [comment]
Hi @Dominik-Kuzila 

Thank you for the pull request. I see no reason not to accept this. Just need two things fixed first,

A) can you please address the linting error. https://github.com/nextcloud/contacts/actions/runs/11543509232/job/32128715557?pr=4197

B) can you please squash all your commits in to a single commit.

C) please sign your git commit with git commit -sm 'fix: validate group name'

**Comment by Dominik-Kuzila** [comment]
Hi, thank you for responding. Please let me know if I fixed it correctly or if there's anything else I should fix.

**Review by hamza221 — CHANGES_REQUESTED** [review]
Looks good, can you please add a `.catch` here 
https://github.com/nextcloud/contacts/blob/fd93300144dda20d766e9aa1707edc7f0663c3d5/src/components/AppNavigation/RootNavigation.vue#L396

**Comment by SebastianKrupinski** [comment]
@Dominik-Kuzila Thank you for addressing items, Please also add the try/catch for the line that @hamza221 specified, and maybe pop up an error for the user. 

```
showError(t('contacts', 'The message'))
```

showError() shows the error, t() is for translation.

**Review by SebastianKrupinski — APPROVED** [review]
Tested. Work good.

**Review by hamza221 — APPROVED** [review]

**Pull request merged**
