### PR TITLE
Check for Read only addressbooks

### LINKED ISSUE #614: [Vue] Popover menu for Addressbook settings
- [x] Copy link
- [x] Download
- [x] Rename
- [x] Enabled
- [x] Delete
- [X] Move the rename into the popovermenu (similar to like we do on the new Folder button on files. capture d ecran_2018-09-04_22-57-12
- [x] Solution for if the user deletes the last addressbook
- [x] Conditional check on the computed for the menu
    ``` js
    if (addressbooks.length > 1) {
        menu.push({itemObject})
    }
    ```
    *example, you cannot change the enable state of a readonly addressbook, nor rename it*
- [X] If an ab is readonly, you should not be able to: rename
- [X] If an ab is readonly, you should not be able to: enable/disable
- [x] If rename has been trigged and popover menu is closed it needs to reset renaming to false.
- [x] Add loading states for the rename/delete/state change
- [x] Add WebDav checks - failure on the dispatch, `then` is if everything is ok (we'll have to use catch in a near future)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/62849606-vue-popover-menu-for-addressbook-settings?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sleepypioneer**
Partial fix #614 WIP I've added the checks for the read only however the addressbooks dont have a readonly attribute so I have hard coded it in for now.

### CODE REVIEW

**Comment by skjnldsv** [comment]
> however the addressbooks dont have a readonly attribute

You can add one then ;)

**Comment by sleepypioneer** [comment]
True, was over thinking it - trying to get it up before I left, XD

**Comment by skjnldsv** [comment]
Since we're at it, could you also fix my error here: https://github.com/nextcloud/contacts/blob/c9155e4d44f012de649ad04a13901fba7a69c58a/src/components/ContentList/ContentListItem.vue#L13

We're supposed to use `readOnly`, not `enabled` :see_no_evil:

**Comment by skjnldsv** [comment]
And bonus: https://github.com/nextcloud/contacts/blob/c9155e4d44f012de649ad04a13901fba7a69c58a/src/views/Contacts.vue#L111

:heart:

**Comment by sleepypioneer** [comment]
Alrighty then! Made those changes @skjnldsv

**Pull request merged**
