### PR TITLE
Migrate app bootstrapping

### PR DESCRIPTION
**Pull request by kesselb**
**Todo** 

- [x] Make sure https://github.com/nextcloud/contacts/pull/1687 still works (PatchPlugin for Sabre)
- [x] Integration into files app works

**Test plan**

- [x] Open files app: Use contact integration on the upper right
- [x] Create contact
- [x] Update contact
- [x] Delete contact
- [x] Contact: Download
- [x] Contact: Import
- [x] Contact: Generate QR code
- [x] Create group and add a member
- [x] Delete group (=> unset the group for each member)
- [x] Group: Download
- [x] Group: Import
- [x] Create address book
- [x] Delete address book
- [x] Rename address book
- [x] Address book: Download

### CODE REVIEW

**Comment by kesselb** [comment]
> Contact: Generate QR code

I see a QR code ;) But don't know what tool/app could read it ...

**Comment by skjnldsv** [comment]
> I see a QR code ;) But don't know what tool/app could read it ...

Any qrcode reading app :grin:

**Comment by kesselb** [comment]
> > I see a QR code ;) But don't know what tool/app could read it ...
> 
> Any qrcode reading app grin

Thanks ;) I did another test with a different qr reader and it works :sunglasses:

**Comment by kesselb** [comment]
> Group: Download

Is broken (also on master)

**Comment by kesselb** [comment]
>  Group: Import

Tricky to test: Create an address book, Add a contact, Add a group for the contact, Export the address book, Delete the address book. Reload the page. Import the vcf. Now contact and group should be back.

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
