### PR TITLE
Migrate template to form

### PR DESCRIPTION
**Pull request by GretaD**
- [x] Contacts bug report
- [x] Circles bug report
- [x] Feature request

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
We can probably simplify this form in the future :+1:

**Comment by GretaD** [comment]
@ChristophWurst you wanted me to add the form from circles and the feature request in this PR, right?

**Comment by GretaD** [comment]
test here: https://github.com/GretaD/dummy-repository/issues

how that section in the end looks like. I would say to remove it

**Review by ChristophWurst — APPROVED** [review]
Looks good

**Pull request merged**
