### PR TITLE
Show contacts without fn

### PR DESCRIPTION
**Pull request by irgendwie**
This firstly removes the property filter for syncing addressbooks, meaning contacts without fn are now also synced.
Secondly, the value of n was automatically joined and inserted into the visual fullname, this is now visually improved.

@Henni @jancborchardt

### CODE REVIEW

**Comment by irgendwie** [comment]
Fixes some bugs:

https://github.com/owncloud/contacts/issues/485
https://github.com/owncloud/contacts/issues/403

**Comment by MariusBluem** [comment]
This is very cool 👍 ... I'll love to see my macOS adressbook without all these "Without Title" contacts    😜

**Comment by jancborchardt** [comment]
Can you review if this fixes the issues you encountered? :) @bart-1 @steinjer @aspdye @skjnldsv

**Comment by skjnldsv** [comment]
This is a bad Idea! Than means we allows non valid vcards.
Right now we never allowed such thing, and made sure we couldn't generate vcard that are not rfc-compliant. I haven't tested it right now, but we can't allow that in our system.

**Comment by steinjer** [comment]
@skjnldsv: No! It is a bad idea to delete my imported vcards without any warning or error! 
Many client programs ignore the "non valid vcard" and handle empty fn properties. 
If the fn property is necessary, the contact app could fill it with default value like "formatted text is empty".

**Comment by skjnldsv** [comment]
@steinjer It's not deleted, it's juste not synced.

**Comment by Henni** [comment]
@skjnldsv I think we should apply the robustness principle:
> be conservative in what you do, be liberal in what you accept from others.

So in my opinion we should accept "broken" vcards without fn during an import or from webdav (if another client uploaded them) and display them in our app. But we should never create such a vcard ourselves. This means our frontend shouldn't allow to submit a new contact if the fn field isn't filled out.

This should also apply for all other fields, btw. For example this means we should try to handle broken date formats, but always create correct date formats ourselves. (I know that this currently isn't the case, thanks to our vcard lib)

**Comment by skjnldsv** [comment]
@irgendwie Right now with your pr, what does the contact look like in the app if it doesn't have a FN field set?

**Comment by irgendwie** [comment]
@skjnldsv Since we already have https://github.com/nextcloud/contacts/commit/ed1659dd49d475fcf554ad3c3d0bddb9b25b20c5, contacts without a fullname would be loaded, the contents of name would be concatinated and stored in fullname.
So this PR would simply load contacts without a fullname, since we obviously need to take care of this case.

**Comment by skjnldsv** [comment]
In this case bug 👍 🎉 
But we should really be careful about broken vcard anyway :)

**Pull request merged**
