### PR TITLE
Use localcontact as default changes on properties

### LINKED ISSUE #1044: New contact: TEL, EMAIL and ADR cannot be removed together
### Describe the bug

After creating a new contact in Nextcloud Contacts, the initial `ADR`, `EMAIL` and `TEL` can not be removed together, but only one at a time, requiring a reload after each removal.

(I noticed this when trying to create a birthday-only contact.)

**To Reproduce**
1. Create a new contact and rename (e.g. Test):
```
BEGIN:VCARD
VERSION:4.0
PRODID:-//Nextcloud Contacts v3.0.5
UID:0ae196d4-bfaa-4756-a436-7ddad29d04a1
REV;VALUE=DATE-AND-OR-TIME:20190407T142905Z
FN:Test
ADR;TYPE=HOME:;;;;;;
EMAIL;TYPE=HOME:
TEL;TYPE="HOME,VOICE":
END:VCARD
```
2. Notice that the new contact initially has phone (`TEL`), email (`EMAIL`) and address (`ADR`), as shown in the UI in this order.
3. Delete the phone (`TEL`). [It works.]
4. Delete the email (`EMAIL`). [Does **not** work.]
5. Delete the address (`ADR`). [Does **not** work.]
6. Reload the page. [Phone is gone as expected, but email and address are still there.]
7. Delete the email (`EMAIL`). [It works.]
8. Delete the address (`ADR`). [Does **not** work.]
9. Reload the page again. [Email is gone as expected, but address is still there.]
10. Delete the address (`ADR`) [It works.]

**Expected behavior**
It should be possible to delete phone, email and address in one go.

**Actual behavior**
Deleting more than one of phone, email and address requires a reload.

**Screenshots**
n/a

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** 15.0.6

**Contacts version:** 3.0.5

**Updated from an older Nextcloud or fresh install:** Updated

**Signing status:**
n/a

**List of activated apps:**
n/a

**Nextcloud configuration:**
n/a

### Client configuration
**Browser:** Firefox 66.0.2

**Operating system:** Linux

**CardDAV-clients:** n/a

#### *Web server error log*
(omitted)

#### *data/nextcloud.log*
(omitted)

#### Browser log
```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
```

The network log includes a `PUT` for each deletion, but all `PUT`s have the same params and the successful return code `204`.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/72508164-new-contact-tel-email-and-adr-cannot-be-removed-together?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #1044 

@rponline @caugner

### CODE REVIEW

**Comment by rponline** [comment]
Ok, it's working!

The only thing worth mentioning:  
The viewport always scrolls on top when deleting a property.

**Comment by skjnldsv** [comment]
@rponline nice catch! :)
We need to prevent the action indeed!

**Comment by skjnldsv** [comment]
@rponline fix is in https://github.com/nextcloud/nextcloud-vue/pull/342

**Comment by rponline** [comment]
I somehow can't use a custom version of nexcloud-vue.

**Comment by skjnldsv** [comment]
@rponline just do `make` :)

**Comment by rponline** [comment]
I can't test this for reasons I don't understand.

after using npm link, the `contacts` JS is not compiling anymore:
image



Without using npm link (and just copying the `dist/` content), js compiles, but the contacts app is not working anymore: It just stops doing stuff and shows a blank page: 

image

Same behavior when i just use the master branch of nextcloud-vue ...  
I don't know what's wrong with my environment or what I'm doing wrong.

Someone else should test it instead, please :) (@caugner ?)

**Comment by skjnldsv** [comment]
Hum, I had that once.
Ignore it, yo can still test this pr without the nextcloud-vue part.

Just ignore the viewport issue, i'll be fixed automatically once we released a new nextcloud-vue release :)

**Comment by rponline** [comment]
Ignoring the whole scrolling issue:  
yes, it's working :)

**Pull request merged**
