### PR TITLE
shortened addressbook entries

### PR DESCRIPTION
**Pull request by pgys**
part of #14

### CODE REVIEW

**Comment by MariusBluem** [comment]
_Tip: Make sure, that `info@pexlab.space` is associated to your GitHub account, so that the commit is associated to your profile 😉_

**Comment by jospoortvliet** [comment]
Any review here, @georgehrke @jancborchardt @jakobsack ?

**Comment by georgehrke** [comment]
The css fix itself works 

But there is one issue: Can you please add a title attribute to the element, so user can see the complete name on hover? :)  

Here are two screenshots for @jancborchardt ;)
before:
contacts - nextcloud chromium today at 3 07 44 pm
after:
contacts - nextcloud chromium today at 3 09 09 pm

**Comment by irgendwie** [comment]
@georgehrke Added the title

**Comment by Henni** [comment]
:+1:

**Pull request merged**
