### PR TITLE
Fix grouplist height

### PR DESCRIPTION
**Pull request by skjnldsv**
Might not be needed if this only occurs on core master since nextcloud/server#3260 has a fix for that.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> Might not be needed if this only occurs on core master since nextcloud/server#3260 has a fix for that.

Then let's wait for the server PR and close this then? :-P

**Comment by skjnldsv** [comment]
It's also on stable11 apparently, so we still need this I think?

**Comment by ChristophWurst** [comment]
Okay, I'd rather fix this here then instead of backporting too much.

**Comment by ChristophWurst** [comment]
How can I test this?

**Comment by skjnldsv** [comment]
Well, to really a test, but since we have the new contact button that is 68px high, we need to calc the 100% minus the new button height! ^^
capture d ecran_2017-01-26_19-02-56

**Comment by skjnldsv** [comment]
capture d ecran_2017-01-26_19-03-36

**Pull request merged**
