### PR TITLE
Fix avatar display on read-only contacts and use global Avatar component

### PR DESCRIPTION
**Pull request by skjnldsv**
| Before | After |
|:---------:|:------:|
|Kazam_screenshot_00004|Kazam_screenshot_00003|

### CODE REVIEW

**Review by call-me-matt — CHANGES_REQUESTED** [review]
Looks very nice!
Unfortunately I cannot change the avatar anymore:

<details>
<summary>console error</summary>

```
Error: 
    r dist.js:1
    r dist.js:1
    o dist.js:1
    t dist.js:1
    n dist.js:1
    onreadystatechange dist.js:1
    e dist.js:1
    e dist.js:1
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    me dist.js:1
    i dist.js:1
    de dist.js:1
    de dist.js:1
    value dist.js:1
    e dist.js:1
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    me dist.js:1
    i dist.js:1
    de dist.js:1
    de dist.js:1
    value dist.js:1
    e dist.js:1
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    ke dist.js:1
    i dist.js:1
    Se dist.js:1
    Se dist.js:1
    value dist.js:1
    n contacts.js:349
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    Yn contacts-main.js:1586
    i contacts-main.js:1586
    Gn contacts-main.js:1586
    Gn contacts-main.js:1586
    updateContact contacts.js:325
    f vuex.esm.js:847
    dispatch vuex.esm.js:512
    dispatch vuex.esm.js:402
    setPhoto ContactDetailsAvatar.vue:342
    e ContactDetailsAvatar.vue:255
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    T contacts-main.js:600
    i contacts-main.js:600
    E contacts-main.js:600
    E contacts-main.js:600
    onloadend ContactDetailsAvatar.vue:223
    processFile ContactDetailsAvatar.vue:223
    VueJS 3
contacts.js:353:12
    n contacts.js:353
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    Yn contacts-main.js:1586
    a contacts-main.js:1586
    (Async: promise callback)
    Yn contacts-main.js:1586
    i contacts-main.js:1586
    Gn contacts-main.js:1586
    Gn contacts-main.js:1586
    updateContact contacts.js:325
    f vuex.esm.js:847
    dispatch vuex.esm.js:512
    dispatch vuex.esm.js:402
    setPhoto ContactDetailsAvatar.vue:342
    e ContactDetailsAvatar.vue:255
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    T contacts-main.js:600
    i contacts-main.js:600
    E contacts-main.js:600
    E contacts-main.js:600
    onloadend ContactDetailsAvatar.vue:223
    (Async: EventHandlerNonNull)
    processFile ContactDetailsAvatar.vue:223
    VueJS 3
        Ye
        n
        _wrapper
``` 
<details>

**Comment by skjnldsv** [comment]
Is this related to this pr?
Any requests error?

**Comment by call-me-matt** [comment]
> Is this related to this pr?

I believe so, as it's not happening on master.

> Any requests error?

here some logs, don't know if this helps

<details>
<summary>network log</summary>

```

HTTP/2 204 No Content
server: nginx/1.17.10
date: Tue, 13 Oct 2020 14:11:41 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
content-security-policy: default-src 'none';
etag: "e8c957c28b815b4580258da61d38af6c"
oc-etag: "e8c957c28b815b4580258da61d38af6c"
referrer-policy: no-referrer
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: none
x-xss-protection: 1; mode=block
X-Firefox-Spdy: h2

```
</details>

<details>
<summary>nextcloud.log</summary>

```bash
{"reqId":"tqhh4dhF8jkuE5sLfns0","level":0,"time":"2020-10-13T14:08:22+00:00","remoteAddr":"172.22.0.1","user":"admin","app":"contacts","method":"PUT","url":"/remote.php/dav/addressbooks/users/admin/contacts/491F6885-BFB6-4572-8A74-4D85F5B77C51.vcf","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"21.0.0.1"}
{"reqId":"tqhh4dhF8jkuE5sLfns0","level":0,"time":"2020-10-13T14:08:22+00:00","remoteAddr":"172.22.0.1","user":"admin","app":"files_sharing","method":"PUT","url":"/remote.php/dav/addressbooks/users/admin/contacts/491F6885-BFB6-4572-8A74-4D85F5B77C51.vcf","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"21.0.0.1"}
{"reqId":"tqhh4dhF8jkuE5sLfns0","level":0,"time":"2020-10-13T14:08:22+00:00","remoteAddr":"172.22.0.1","user":"admin","app":"PHP","method":"PUT","url":"/remote.php/dav/addressbooks/users/admin/contacts/491F6885-BFB6-4572-8A74-4D85F5B77C51.vcf","message":{"Exception":"Error","Message":"Calling the \"Symfony\\Component\\EventDispatcher\\EventDispatcherInterface::dispatch()\" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead. at /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php#58","Code":0,"Trace":[{"function":"onAll","class":"OC\\Log\\ErrorHandler","type":"::","args":[16384,"Calling the \"Symfony\\Component\\EventDispatcher\\EventDispatcherInterface::dispatch()\" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.","/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",58,{"event":"\\OCA\\DAV\\CardDAV\\CardDavBackend::updateCard","eventName":{"__class__":"OC\\EventDispatcher\\GenericEventWrapper"}}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":58,"function":"trigger_error","args":["Calling the \"Symfony\\Component\\EventDispatcher\\EventDispatcherInterface::dispatch()\" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.",16384]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":85,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["\\OCA\\DAV\\CardDAV\\CardDavBackend::updateCard",{"__class__":"OC\\EventDispatcher\\GenericEventWrapper"}]},{"file":"/var/www/nextcloud/apps/dav/lib/CardDAV/CardDavBackend.php","line":760,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->","args":["\\OCA\\DAV\\CardDAV\\CardDavBackend::updateCard",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/CardDAV/Card.php","line":98,"function":"updateCard","class":"OCA\\DAV\\CardDAV\\CardDavBackend","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1143,"function":"put","class":"Sabre\\CardDAV\\Card","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":515,"function":"updateFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":325,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":98,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"21.0.0.1"}
{"reqId":"tqhh4dhF8jkuE5sLfns0","level":1,"time":"2020-10-13T14:08:22+00:00","remoteAddr":"172.22.0.1","user":"admin","app":"no app in context","method":"PUT","url":"/remote.php/dav/addressbooks/users/admin/contacts/491F6885-BFB6-4572-8A74-4D85F5B77C51.vcf","message":"Deprecated event type for \\OCA\\DAV\\CardDAV\\CardDavBackend::updateCard: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"21.0.0.1"}
```
</details>

**Comment by skjnldsv** [comment]
Done :)

**Comment by call-me-matt** [comment]
Almost perfect. Only in the list view of the person I share my contacts with, the avatars are either not shown or blanked out. In the details-header, the avatar is shown correctly. No error logs beside `The following contact has been repaired: invalid REV`

**Comment by skjnldsv** [comment]
> Only in the list view of the person I share my contacts with, the avatars are either not shown or blanked out.

So as UserA, you share an addressbook with UserB and UserB cannot see avatars in the list?
Can you inspect the html of the Avatar in the list and copy/paste it here?

**Comment by call-me-matt** [comment]
> So as UserA, you share an addressbook with UserB and UserB cannot see avatars in the list?

Unfortunately yes.

> Can you inspect the html of the Avatar in the list and copy/paste it here?

1. At first loading, all avatars (in the list) are letters:
Bildschirmfoto von 2020-10-19 22-22-05

2. once clicked `Mr. Test` turns white
Bildschirmfoto von 2020-10-19 22-22-38

3. while `Mr. Hello` remains a letter.
Bildschirmfoto von 2020-10-19 22-23-01

**Comment by skjnldsv** [comment]
Fixed @call-me-matt ! :)

**Review by call-me-matt — APPROVED** [review]
Wonderful.
APPROVED.

**Pull request merged**
