### PR TITLE
Make sure to properly set the month to the same start index than JS and moment

### LINKED ISSUE #796: Calendar interface unable to select / print the proper date
The calendar app is unable to set the proper birth date. The person is born 28th dec 1928. Whenever I try to select that date in the Web interface, the sub menu closes and shows a date in November. I did again, no luck. Clicked on the month itself, tried any other date in Dec 1928, nothing is doing.

I deleted the field and switched to my iPad which sync the contacts over CardDav. I configured the date properly there. Back in the web interface, the date re-appeared but again, in the month of November instead of December.

-Update :
Forgot to mention that contact imported from VCF files with a brith date in December are showed properly. Difference is that when imported, the field mentions only the day itself, no hour, while when setting it from the Web Interface, the interface requires an hour.

-End of the update...

### Steps to reproduce
1. Go in a contact without a birth date
2. Set it for 28 Dec 1928
3. See the saved result as being marked for November instead of December

### Expected behaviour
Have the proper date configured and printed in the contact...

### Actual behaviour
Date is switched back one month, to November.

### Server configuration
Nextcloud Docker, latest

**Operating system**:
Alpine

**Web server:**
Apache

**Database:**
MariaDB, separate docker on a different server

**PHP version:**
Docker image nextcloud:latest....

**Nextcloud version:** (see Nextcloud admin page)
15.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Downloaded the nextcloud:latest image from Docker Hub, using Portainer

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - audioplayer: 2.5.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.0
  - dav: 1.8.0
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - music: 0.9.3
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.2
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_saml: 2.1.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - twofactor_rcdevsopenotp
  - user_external</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud-dev.jblan.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "overwrite.cli.url": "https:\/\/cloud-dev.jblan.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.8.2",
            "types": "filesystem"
        },
        "audioplayer": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "25"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.6.4",
            "types": ""
        },
        "checksum": {
            "enabled": "yes",
            "installed_version": "0.4.2",
            "types": "filesystem"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.0.0",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1545441990.4587",
            "lastcron": "1545493801",
            "lastupdatedat": "1545441990.4629",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "db81cddf52fdb3c8ca1e4c859e214124",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "external": {
            "enabled": "yes",
            "installed_version": "3.2.0",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.2.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "0.11.0",
            "types": ""
        },
        "music": {
            "enabled": "yes",
            "installed_version": "0.9.3",
            "types": "filesystem"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.5.1",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "skey": "1545442188622",
            "types": "filesystem"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "5.0.0",
            "stun_servers": "[\"stun.nextcloud.com:443\"]",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "user_saml": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "types": "authentication"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        }
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

Data are on an NFS Share from FreeNAS. The share is mounted by Alpine and mounted as a BIND volume in the container.

**Are you using encryption:** yes/no

No encryption (yet...)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No ; users are locally managed by Nextcloud itself

### Client configuration
**Browser:**

Chrome

**Operating system:**

MacOS X

### Logs
#### Web server error log
<details>

No web errors...

</details>

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/67958958-calendar-interface-unable-to-select-print-the-proper-date?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #796

@j-ed @Heracles31

[contacts.tar.gz](https://github.com/nextcloud/contacts/files/2727438/contacts.tar.gz)

### CODE REVIEW

**Comment by j-ed** [comment]
@skjnldsv

> [contacts.tar.gz](https://github.com/nextcloud/contacts/files/2727438/contacts.tar.gz)

I've just downloaded the archive and used it to update my Nextcloud test instance. Could it be possible that it doesn't contain your patch, because I cannot see any change in the behaviour?

**Comment by skjnldsv** [comment]
@j-ed have you cleared your cache? :)

**Comment by j-ed** [comment]
> @j-ed have you cleared your cache? :)

Ok, I've to admit you're right 🤕 I restarted the server, restarted the browser, but have forgotten to explicitly press the clear cache button. The good news is, it is working now. I was able to select dates in December and January without any further problems.

**Comment by skjnldsv** [comment]
@j-ed awesome!! Thanks for your help :)

**Pull request merged**
