### PR TITLE
Uppercase labels too

### LINKED ISSUE #67: Contact app should handle field labels correctly also if written in lowercase
## Expected behavior

The Contacts app should handle phone number or email labels correctly, independently if they're stored in one or multiple lines or written in lowercase.

## Current behavior

The Contacts app doesn't handle phone number or email labels correctly if they're stored in one or multiple lines or written in lowercase. Instead strange labels will be displayed in a contact record.
Additionally it is not possible to correct these records using the web GUI. The field label will be kept unchanged. If you export a contact record to vcf-file, manually delete the `X-ABLABEL` field and reimport the vcf-file the field labels can be edited again using the web GUI.

Example:

20161225_nc_home_prefs
20161225_nc_cell_prefs
```
3V1RRX.TEL;TYPE=HOME\,VOICE:+49 2222 3333333
3V1RRX.X-ABLABEL:home\,pref

IX9FXH.TEL;TYPE=CELL:+49 2222 3333333
IX9FXH.X-ABLABEL:cell\,pref

KX0S98.TEL:+49 2222 3333333
KX0S98.X-ABLABEL:work,pref
```

### Steps to reproduce
1. Import a vcf file which contains the mentioned syntax.
2. Try to change the field labels using the web GUI.

#### Server Configuration

OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 10.0.2
Contacts app: 1.5.2
#### Client Configuration

Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40386340-contact-app-should-handle-field-labels-correctly-also-if-written-in-lowercase?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #67 
Test vcf: [cd159d83-5833-44ec-a3df-1e91b085ef28.txt](https://github.com/nextcloud/contacts/files/1355160/cd159d83-5833-44ec-a3df-1e91b085ef28.txt)

### CODE REVIEW

**Comment by skjnldsv** [comment]
@xh3n1 I don't think either. I'm an idiot! 😂

**Comment by skjnldsv** [comment]
@xh3n1 ok now!

**Comment by jancborchardt** [comment]
Fully capitalizing looks veeery screamy and out of place. ;) We should just use »Home«, »Work«, »Mobile«, »Work pager«, »Telex«, »Home fax«, »Fax« etc.

**Comment by skjnldsv** [comment]
@jancborchardt did you test the pr? ^^'

**Comment by jancborchardt** [comment]
@skjnldsv sorry, I looked at the comment in https://github.com/nextcloud/contacts/issues/67#issuecomment-329672586 and assumed that’s how it’s going to be displayed. ;)

**Comment by skjnldsv** [comment]
@jancborchardt Don't worry, made me laugh! 😝 ❣️

**Comment by jancborchardt** [comment]
I'm happy to entertain :D

**Pull request merged**
