### PR TITLE
Resize maximum dimensions for pictures coming from SocialApiService

### LINKED ISSUE #2743: Contact has 161 MB because of (automated) social media avatar
### Describe the bug

I noticed out of memory errors on my phone related to DavX5 synchronization (Nextcloud <-> Android). After digging around for a few hours, I saw that one of my Nextcloud contacts has 161MB because of an avatar that was downloaded automatically. The VCF file shows

```
PHOTO;ENCODING=B;TYPE=PNG;VALUE=BINARY:iVBORw0KGgoAAAANSUhEUgAAAtAAAALQCAYA
 AAC5V0ecAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAgAElEQVR42sy92ZIkObIldhSAmW+RGblU1n
```

and then endless lines of photo data.

Has this been an issue for other users? Did you already encounter such a problem?

Thanks for looking into this!

### Steps to reproduce

I didn't do anything special. Just added the contact a while ago. (Email, and name).

### Expected behavior

Avatars are small.

### Actual behavior

Avatar has 161MB.

### Contact version

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Operating system

_No response_

### List of activated Apps

```shell
Contacts.
```

### Nextcloud Signing status

_No response_

### Configuration report

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by tcitworld**
Closes #2743

Make sure every picture fetched from SocialAPIService has a maximum size of 256 pixels.

Should we add an extra condition to reject on size being to high?

Would be nice to test ImageResizer with a few test pictures too.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
You get bonus points for declare(strict_types=1); ;-)

**Review by call-me-matt — APPROVED** [review]
good idea.

**Comment by call-me-matt** [comment]
But I am not sure it closes https://github.com/nextcloud/contacts/issues/2743 completely -
I would like to make sure there are not images piling up instead of being replaced by newer versions.

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
