### PR TITLE
Fix rename types in propreties

### LINKED ISSUE #3738: Modified Text on Labels of fields are not stored in db or shown from db anymore in contacts since nc26
### Describe the bug

On modifing a label for example Telefon -> MyTelefon or an address lable Address -> privateAddress this is not shown again after saving, changing the dataset an recalling the modified contact.

01 editing-dataset
02 saved-dataset_after-editing
03 dataset-after-recalling
04 dataset seen by cardbook via carddav

Dataexport via carddav also seems not working well.

This effect or behavior was not before nc26. Since nc26 and nc27 (also on different systems) the problems existing.

### Steps to reproduce

1. Go to contacts
2. Click on new oder edit contact
3. modify label e.g. "Telefon" throug "Haustelefon" 
4. save dataset
5. change dataset
6. recall created or modified dataset
7. take a look on modified label

take a look on the tree pictures.

### Expected behavior

the content of the modified label is lost
"Haustelefon" shoud shown on label

expected behavior should be "02 saved-dataset_after-editing.jpg"

### Actual behavior

"privat" is schown instead of "Haustelefon"

take a look on "03 dataset-after-recalling.jpg"

### Contact version

5.5.0

### Operating system

NC27 - debian-bullseye

### PHP engine version

Other

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

php8.2.13

### PR DESCRIPTION
**Pull request by hamza221**
fix #3738

### CODE REVIEW

**Review by GretaD — APPROVED** [review]

**Comment by GretaD** [comment]
do we need a backport?

**Comment by hamza221** [comment]
It was introduced here  #3374

**Pull request merged**
