### PR TITLE
increase the number of open dependabot PRs as the number is already r…

### PR DESCRIPTION
**Pull request by szaimen**
…eached

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by GretaD — APPROVED** [review]
i would prefer to work on the tickets instead of increasing the number, but yes, maybe 10 its a bit low

**Comment by ChristophWurst** [comment]
I would also say we need to work on the backlog. More open PRs will cause more rebase dances and waisted CI resources

**Comment by szaimen** [comment]
Fine by me 👍

**Comment by GretaD** [comment]
so lets close this pr then?

**Comment by miaulalala** [comment]
Closing this as discussed

**Pull request closed without merging**
