### PR TITLE
Bump @nextcloud/vue v7.0.0-beta.3

### PR DESCRIPTION
**Pull request by GretaD**
Signed-off-by: greta <gretadoci@gmail.com>

### CODE REVIEW

**Comment by GretaD** [comment]
this is the only problem i noticed while upgrading but please test
Screenshot from 2022-09-13 16-19-39

**Comment by ChristophWurst** [comment]
- [ ] BUG contacts are not listed anymore

Bildschirmfoto vom 2022-09-14 15-46-19

**Comment by ChristophWurst** [comment]
Please rebase for https://github.com/nextcloud/contacts/pull/2928

**Review by ChristophWurst — APPROVED** [review]
Looks ok

**Pull request merged**
