### PR TITLE
feat(deps): Revive PHP7.4 support

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/contacts/issues/3244

### CODE REVIEW

**Review by st3iny — APPROVED** [review]
Tested and works.

**Comment by ChristophWurst** [comment]
Let's just release as v5.2

**Comment by st3iny** [comment]
> Let's just release as v5.2

Yeah, I just saw the RC. Sorry for the ping. :sweat_smile:

**Pull request merged**
