### PR TITLE
Rephraze "There is no member in this circle"

### PR DESCRIPTION
**Pull request by aryatalathi**
Fixes https://github.com/nextcloud/contacts/issues/2284

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Looks good. Thanks!

Please squash your commits

**Comment by ChristophWurst** [comment]
> [aryatalathi](/aryatalathi) requested a review from [ChristophWurst](/ChristophWurst)

See https://github.com/nextcloud/contacts/pull/3133#pullrequestreview-1215045229

**Comment by aryatalathi** [comment]
> See [#3133 (review)](https://github.com/nextcloud/contacts/pull/3133#pullrequestreview-1215045229)

Can't squash 2 commits as 1 commit's changes was made by me on GitHub itself and other was committed through VS code. It's giving some error. Sorry :(

**Comment by ChristophWurst** [comment]
I've squashed the commits for you

**Comment by aryatalathi** [comment]
> I've squashed the commits for you

Thank you very much!!

**Pull request merged**
