### PR TITLE
Read-only addressbook improvements 

### LINKED ISSUE #294: Create a read-only view of a contact
... for read-only shared addressbooks

Bugs fixed by this:
- Contacts edition is possible on some fields 
- No move to r/o addressbook allowed

### PR DESCRIPTION
**Pull request by skjnldsv**
- [x] Remove addressbook from the move select
- [x] Remove addressbook from the import select
- [x] Disable import if the only addressbook available is in read-only mode
- [x] Create read-only view for contacts in read-only addressbooks, fix #294

### CODE REVIEW

**Comment by skjnldsv** [comment]
This is done on purpose since the read only details page for those type of user will completely remove this dropdown :)

kazam_screenshot_00000

**Comment by skjnldsv** [comment]
Hum, 1d1ccdaee724091f5c1000ded07f5dafd20028f6 broke the import

**Comment by skjnldsv** [comment]
Added readOnly details
contacts nextcloud 1
contacts nextcloud

**Comment by Henni** [comment]
I'm a bit late to the party, but why did you create a separate readonly template for every existing template?
Couldn't we simply integrate this into the existing templates?

Something like:
```html
<input [...] ng-disabled="ctrl.addressBook.readOnly">
```

**Comment by skjnldsv** [comment]
Tried that already, didn't liked the idea since a user can manually edit the field to remove the disabled state. But yes, I can push those commit if you prefer. I kind of like not having two templates too. :)

**Comment by skjnldsv** [comment]
@Henni @irgendwie Done! Switch to previous commits.
Works fine too now! :)

**Pull request merged**
