### PR TITLE
Updating lint-php.yml workflow from template

### PR DESCRIPTION
**Pull request by nextcloud-command**
Automated update of the lint-php.yml workflow from https://github.com/nextcloud/.github

### CODE REVIEW

**Review by miaulalala — APPROVED** [review]

**Review by miaulalala — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by ChristophWurst** [comment]
@miaulalala @skjnldsv this means we won't lint 7.3 anymore and syntax errors could sneak into the next release, similar to https://github.com/nextcloud/calendar/pull/3755.

**Comment by skjnldsv** [comment]
Wanna revert?

**Comment by ChristophWurst** [comment]
I'd prefer that until we have a better solution :)

**Comment by ChristophWurst** [comment]
A full revert is maybe too much. The lint summary change is still good. I'd suggest we only fix the matrix to include 7.3 again.

**Pull request merged**
