### PR TITLE
chore: drop support for PHP 7.4

### PR DESCRIPTION
**Pull request by kesselb**
Ref https://github.com/nextcloud/groupware/issues/41

# TODO

- [x] Adjust required checks

### CODE REVIEW

**Review by st3iny — COMMENTED** [review]
PHP CS issues should be fixable automatically. The phpunit error is weird:

`
Generating code coverage report in Clover XML format ... SebastianBergmann\CodeCoverage\StaticAnalysis\CodeUnitFindingVisitor::unionOrIntersectionAsString(): Argument #1 ($type) must be of type PhpParser\Node\ComplexType, PhpParser\Node\UnionType given, called in /home/runner/work/contacts/contacts/apps/contacts/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CodeUnitFindingVisitor.php on line 184
`

**Comment by st3iny** [comment]
It works on https://github.com/nextcloud/contacts/actions/runs/3854609590/jobs/6568778952 for php8.0. Maybe combining both PR will do the trick?

**Comment by st3iny** [comment]
PR at https://github.com/nextcloud/server/pull/36137 needs a backport o stable25 to fix CI. Or is there a better way?

**Comment by ChristophWurst** [comment]
> PR at [nextcloud/server#36137](https://github.com/nextcloud/server/pull/36137) needs a backport to stable25 to fix CI. Or is there a better way?

https://github.com/nextcloud/mail/pull/4194

**Review by ChristophWurst — APPROVED** [review]

**Comment by kesselb** [comment]
> Generating code coverage report in Clover XML format ... SebastianBergmann\CodeCoverage\StaticAnalysis\CodeUnitFindingVisitor::unionOrIntersectionAsString(): Argument #1 ($type) must be of type PhpParser\Node\ComplexType, PhpParser\Node\UnionType given, called in /home/runner/work/contacts/contacts/apps/contacts/vendor/phpunit/php-code-coverage/src/StaticAnalysis/CodeUnitFindingVisitor.php on line 184

Fix: Don't run coverage for stable25 / Update php-parser for master.

**Pull request merged**
