### PR TITLE
Add exception for invalid base64 avatar strings, fix #94

### LINKED ISSUE #94: Failure while importing vcf's (and ics's in calendar app) with more than 16 entries
I run two Nextcloud 11.0.1 server based on an ubuntu 16.04 LTS, oDoidC2, mariadb 10.x, php 7.0 and as well php 7.1 on the other server, both systems are on 64Bit.

One server ist installed from scratch and the other one was upgraded from the early beginning of Nextcloud to the current Nextcloud Release.

I enabled the contact (and calendar) app from the nextcloud appstore within Nextcloud.
Both apps crashed while importing contacts or calendar after the 16. successfull entry.
I had to split the vcf from e.g. 233 into seperate files not consisting of more than 16 contacts per file.
Then the import succeeded for all the files without modifying the content itself.

I can reproduce this behaviour on both systems. Unfortunately nothing is written into the nextcloud logs.

What do you need to investigate further? 
How can i export directly from Nextcloud contacts app?
Should i raise a second issue for the calendar issue either?

Looking forward to your response,
Cheers, Carsten

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #94 
Vcf test: [Test.txt](https://github.com/nextcloud/contacts/files/728085/Test.txt)

If #85 was merged, we could easily add a warning too :)

Before 
capture d ecran_2017-01-24_23-13-01 capture d ecran_2017-01-24_23-12-56

After, no errors in log and
capture d ecran_2017-01-24_23-13-37

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> Merging #102 into master will decrease coverage by 0.02%

Can we have unit tests for this? 😉

**Comment by skjnldsv** [comment]
Eheh! :D

**Comment by skjnldsv** [comment]
@ChristophWurst Here you go ;)

**Comment by ChristophWurst** [comment]
Awesome, thanks :-)

**Comment by skjnldsv** [comment]
@ChristophWurst 
Thank you! 
By the way, I would really want to release the new contacts on time, do you mind to check those?
https://github.com/nextcloud/contacts/milestone/2

**Comment by ChristophWurst** [comment]
Sure, will have a look soon (hopefully this evening)!

**Pull request merged**
