### PR TITLE
fix undefined variables and coding style

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes https://github.com/nextcloud/contacts/issues/47

cc @skjnldsv @jancborchardt @schiessle

### CODE REVIEW

**Comment by skjnldsv** [comment]
Why did it suddenly started to make errors when I could make it on my environment without any problems? 😢 

Anyway, 👍

**Comment by ChristophWurst** [comment]
¯\_(ツ)_/¯

**Comment by jancborchardt** [comment]
@ChristophWurst :D best use of that smiley. And everything works again now.

Only get 2 warnings but not sure if they are crazy:
```
/home/jan/nextcloud/apps/contacts/js/services/contact_service.js
   40:10  warning  Unexpected console statement        no-console
  132:46  warning  Don't make functions within a loop  no-loop-func
```

**Comment by ChristophWurst** [comment]
> Only get 2 warnings but not sure if they are crazy:

I saw those too but have no idea how to fix it

**Pull request merged**
