### PR TITLE
Update contact_service.js

### PR DESCRIPTION
**Pull request by rakekniven**
Changed wording of usermessage. Be less technical. Proposal from user discussion at Transifex.

Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hum, transifex isn't loading here, can you post the discussion?

**Comment by rakekniven** [comment]
See https://www.transifex.com/nextcloud/nextcloud/translate/#nb_NO/contacts/117397326 if it works again.

Discussion as image:

bildschirmfoto 2017-10-07 um 17 21 02

**Comment by skjnldsv** [comment]
Thanks. :) 
I'm not sure about this! Being technical is a good thing here, it really explains the issue. Saying "change anything" just gives me more questions! :)

**Comment by rakekniven** [comment]
Please try to get into the role of user, not developer ;-)
If I am not able to change anything, I miss permissions. "Writing" is technical. 

You are the author, we are the translators. It is up to you :-)

**Comment by skjnldsv** [comment]
Writing is not an incredibly technical term though. I think our current formulation clearly states that it's a permission issue. This pr's edit mislead the user into thinking something went wrong.

**Comment by rakekniven** [comment]
@comradekingu Any thoughts from your side?

**Comment by skjnldsv** [comment]
@nextcloud/contacts

**Comment by irgendwie** [comment]
I suggest:

"You have no permission to make changes to this address book." or simpler "This address book is read-only."

**Comment by rakekniven** [comment]
> "You have no permission to make changes to this address book."

Great and user friendly.

**Comment by skjnldsv** [comment]
Agree! :)

**Comment by rakekniven** [comment]
Should I change my PR?

**Comment by skjnldsv** [comment]
We usually wait for at least two reviews before merging. Since it's a wording issue, it's not that bad. Wait for more next time! 😉

**Comment by comradekingu** [comment]
@rakekniven It is semantics, but i would prefer:
"You lack permission to alter this address book."

**Comment by rakekniven** [comment]
Will do so.

**Pull request merged**
