### PR TITLE
Sort groups alphabetically

### PR DESCRIPTION
**Pull request by ImUrX**
Refers to #522 
I did the solution just giving sort no arguments and overriding toString to each group's name.
Would like to test, but I dont have any idea on how to do so.

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hi, and thanks for your pr! :)
So, instead of changing the behaviour entirely, I would suggest adding a setting under the contacts sorting dropdown (in the bottom left settings area)
What do you think?

**Comment by ImUrX** [comment]
Sure, but which one would be the default one?

**Comment by ImUrX** [comment]
i accidentaly deleted package-lock.json :/

**Comment by ImUrX** [comment]
Gonna remake the whole branch so it’s a little more clean

**Comment by mburnicki** [comment]
I think the entries for "All contacts" and "Contacts without group" shhould be at the top of the list, just like it's now, and below should be a list of all groups, sorted by name.

I don't know what determines the sequence of groups if they are *not* sorted by name (as it's now, unfortunately). This is just confusing if you have many groups, and below them groups like "colleagues-local" "colleagues-external", colleagues-formerly", etc.

And, by the way, when editing a contact, also the selection box should where you can assign the groups should provide the list of group names sorted by name, IMO.

**Pull request closed without merging**
