### PR TITLE
Add Threema as another option for Instant Messenger

### LINKED ISSUE #2716: Support threema as contact type for IM
### Is your feature request related to a problem? Please describe.

I want to store my threema-contact-ID using contacts app.

### Describe the solution you'd like

Enable support of threema inside pulldown of IM widget

### Describe alternatives you've considered

--

### Additional context

--

### PR DESCRIPTION
**Pull request by frlan**
npm run build and test are running on my machine. I wasn't able to test it end-to-end though. 

Fixes #2716

### CODE REVIEW

**Review by st3iny — APPROVED** [review]
Tested and works. Thank you for your contribution :)

Pleas sign-off your commit: https://github.com/nextcloud/contacts/pull/3169/checks?check_run_id=10511652476

**Comment by networkException** [comment]
@frlan are you willing to work on this still?

**Comment by frlan** [comment]
@networkException I have no idea what shall I do. Someone from the core team has to review it and merge it.

**Comment by ChristophWurst** [comment]
The PR has been reviewed already but we can't accept the contribution until you sign it off as your code. See https://github.com/nextcloud/contacts/pull/3169/checks?check_run_id=10511652476 for details.  You have to amend the last commit.

**Comment by st3iny** [comment]
1. Check out this branch and run: `git rebase HEAD~1 --signoff`
2. Then force push it: `git push --force`

**Comment by frlan** [comment]
I'd love to but github is not letting me with a non-saying error message

**Pull request merged**
