### PR TITLE
Remove header color bar as it is not related to the contact

### PR DESCRIPTION
**Pull request by jancborchardt**
Just experimenting with this. Especially as it conflicts with the header bar more and more and it just looks a bit off these days? :)

We should think of another way to focus on the photo and name of the contact, showing them more presently.

### CODE REVIEW

**Comment by jancborchardt** [comment]
What do you think in general @nextcloud/contacts? :)

**Comment by skjnldsv** [comment]
Ah right I forgot about this one :p
Maybe still enphasis the header? Primary color?

Also you can cleanup the `colorAvatar` computed and associated methods in the vue files since we don't need em anymore ;)

**Comment by skjnldsv** [comment]
Also, please rebase ;)

**Comment by jancborchardt** [comment]
> Maybe still enphasis the header? Primary color?

I gave it a bit more whitespace on the top and a tad more on the bottom. I think we need to fix the alignment together with the content below, but something for a separate issue. Since the header directly above is using primary color, I wouldn’t do anything else there.

> Also you can cleanup the `colorAvatar` computed and associated methods in the vue files since we don't need em anymore ;)

Done, thanks for the pointer :)


> Also, please rebase ;)

Done as well :)

**Comment by jancborchardt** [comment]
@nextcloud/contacts please review :)

**Comment by skjnldsv** [comment]
Screenshots? :grin:

**Comment by call-me-matt** [comment]
> Screenshots? grin

grafik

**Comment by jancborchardt** [comment]
> After removing the color bar, I found the contact bubbles quite colorful... A suggestion could be the design from Samsung (or a mix of both)

Let’s keep this separate, as the colored bubbles are used by a lot of different apps. They are in use by Google, Signal, Microsoft etc. and that is for a reason: They help to quickly separate people who didn’t set their avatars, making it much easier to tell people apart in a first-run scenario.

**Comment by skjnldsv** [comment]
There is something that bothers me a little though.
Maybe it's just the change :)
I have a related question though, I remember a discussion about having the avatar as blured background if there was one.
Another question, now that I also think about this: after testing the upcoming grid view in Talk, it looks super similar. Are you sure you don't want to keep the colored background?

**Comment by jancborchardt** [comment]
> Nonetheless, I have a related question: I remember a discussion about having the avatar as blured background if there was one. Is this still something you want?
> Another question, now that I also think about this: after testing the upcoming grid view in Talk, it looks super similar. Are you sure you don't want to keep the colored background?

It just doesn’t work really well with text over it, and takes waaaay too much attention. It works for Talk as that is a specific mode you are in and it is very visual, but is not good for when you want to get info or modify it.

So I’d say: Can we merge it?

**Pull request merged**
