### PR TITLE
Missing border in Contacts

### PR DESCRIPTION
**Pull request by Dennis1993**
I use your demo of NextCloud and founded a missing border. On the left is a grey border for the sidebar. On the next 2 divs is no border anymore. It would be good, if a border is here too to seperate it.

unbenannt-1

### CODE REVIEW

**Comment by MariusBluem** [comment]
Example Screenshot with your Fix: 

bildschirmfoto 2017-03-09 um 20 15 56

**Comment by irgendwie** [comment]
Thank you! :+1:

**Comment by Dennis1993** [comment]
Thank you for your quick feedback!

**Comment by jancborchardt** [comment]
@Dennis1993 thanks for your contribution! :) It would be cool if you can fix it in the server too so it’s also applied to other apps which use this layout (like Mail https://github.com/nextcloud/mail)

You just need to add the code blocks `.app-content-list` (and all below starting with that) as well as `.app-content-detail` into this file: https://github.com/nextcloud/server/blob/master/core/css/apps.scss :)

**Pull request merged**
