### PR TITLE
feat(deps): Add Nextcloud 29 support

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by hamza221** [comment]
We're on rc1  https://github.com/nextcloud/contacts/pull/3714

**Review by ChristophWurst — APPROVED** [review]
I would not drop 25 in here right before branching off. Let's drop 25 for the next minor of Contacts only

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
wrong radio

**Comment by ChristophWurst** [comment]
all previous pre-releases supported 25 so I would keep this until the final

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
