### PR TITLE
Release 5.3.1

### PR DESCRIPTION
**Pull request by hamza221**

### CODE REVIEW

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
info.xml needs a bump too

**Comment by hamza221** [comment]
> info.xml needs a bump too

It is bumped https://github.com/nextcloud/contacts/pull/3455/files#diff-ab97a56738913a50d2334c4d3f10991748d3e29d011f5a674734b63d33d5ce9eR14

**Comment by ChristophWurst** [comment]
I need more coffee. I checked three times.

**Review by ChristophWurst — APPROVED** [review]
Flawless

**Pull request merged**
