### PR TITLE
Create modal window for contacts settings

### LINKED ISSUE #2952: Left sidebar: Move settings to a modal
### Is your feature request related to a problem? Please describe.

The settings in bottom left corner are awkward to use and have some design issues.

image

### Describe the solution you'd like

Move the whole settings section to a modal.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Resolves #2952 

| After | Before |
| --- | --- |
| image| Screenshot from 2022-10-11 14-19-10|

### CODE REVIEW

**Comment by szaimen** [comment]
I just tested this and it seems to work. Only the sort option may not work as expected currently but this may be an already existing issue. (changing sorting between the speicifc options sometimes does not change the contacts order even though it should theoratically be changed in order to reflect the new setting).

| name ordering | surname ordering |
|---|---|
| image | image |

---

Also, can we somehow remove the strange looking border betweeen the input field and the arrow for creating the new address book?

image

---

Also, can we make it more clear when an address book is disabled by addding (disaabled) behind its name then?
really ugly mockup: 
image

**Comment by ChristophWurst** [comment]
One step at a time please @szaimen. Let's move the settings in this PR and keep the redesign for a follow-up.

**Comment by szaimen** [comment]
> One step at a time please @szaimen. Let's move the settings in this PR and keep the redesign for a follow-up.

Fine by me. I'll create a follow-up ticket

**Comment by szaimen** [comment]
Done in https://github.com/nextcloud/contacts/issues/3033

**Review by szaimen — APPROVED** [review]
Tested and works but didn't review the code

**Comment by ChristophWurst** [comment]
@JuliaKirschenheuter are there any blockers for the setting sections?

**Review by ChristophWurst — APPROVED** [review]
Looks great

**Comment by ChristophWurst** [comment]
Please squash

**Pull request merged**
