### PR TITLE
Allow to pick avatar from files + use modal

### LINKED ISSUE #106: Allow assignment of images already in Nextcloud as contact photos
- [ ] If the image is already in Nextcloud, should we really need to upload it again?
- [ ] Provide an editor to cut and resize images like we don on the user settings

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41358489-allow-assignment-of-images-already-in-nextcloud-as-contact-photos?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #106
Capture d’écran_2019-03-29_10-55-09
Capture d’écran_2019-03-29_10-55-27

@jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
@skjnldsv this one was hiding somewhere :D sorry for late reply:

- Loooks soooo great! Much better than the icons without labels we had before. You rock!
- The popovers should be centered (for the one in the viewer, should be to the right as far as possible with some whitespace, just like the user dropdown is). :) The left-alignment looks strange. ;)

**Comment by skjnldsv** [comment]
@jancborchardt I think I remember, but did we not wanted to actually set the popover to center as default? :thinking:

**Comment by jancborchardt** [comment]
@skjnldsv yes, you’re right! It definitely also seems that one of my most given feedbacks on popovers were to center them. :D So seems a good call to make that default.

**Comment by skjnldsv** [comment]
Let's do that on the components then :)

**Pull request merged**
