### PR TITLE
Do not fail hard on initial parsing

### LINKED ISSUE #774: No contacts shown when logged in as admin after update to version 3.0.0
### Steps to reproduce
1. Upgrade contacts to version 3.0.0
2. Log into nextcloud as admin 
3. open contacts app

### Expected behaviour
- The contacts should be visible as before
- It should be possible to create a new contact

### Actual behaviour
- contact list is empty
- it is not possible to add a new contact
- contacts still appear when searching contacts in the upper right corner

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
mysql 5.7.24

**PHP version:**
PHP 7.0.32-0ubuntu0.16.04.1

**Nextcloud version:** (see Nextcloud admin page)
15

**Contacts version:** (see Nextcloud apps page)
3.0.0

**Updated from an older Nextcloud or fresh install:**
updated

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

 Accessibility 1.1.0
Activity 2.8.2
Auditing / Logging 1.5.0
Bookmarks 0.14.3
Calendar 1.6.4
Collaborative tags 1.5.0
Comments1.5.0
Contacts 3.0.0
Default encryption module 2.3.0
Deleted files 1.5.0
Federation 1.5.0
File sharing 1.7.0
First run wizard 2.4.0
Gallery 18.2.0
Log Reader 2.0.0
Markdown Editor 2.0.5
Metadata 0.8.0
Monitoring 1.5.0
Nextcloud announcements 1.4.0
Notifications2.3.0
Password policy 1.5.0
PDF viewer 1.4.0
RainLoop 6.0.2
Share by mail 1.5.0
Support 1.0.0
Tasks 0.9.8
Text editor 2.7.0
Theming 1.6.0
Update notification 1.5.0
Usage survey 1.3.0
Versions 1.8.0
Video player 

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

I have no access to the config at the moment.

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox

**Operating system:**
Arch Linux / Windows

#### Web server error log
```

```
no related errors shown

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/67620338-no-contacts-shown-when-logged-in-as-admin-after-update-to-version-3-0-0?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #774 

@phiL0co can you test? 
[contacts.tar.gz](https://github.com/nextcloud/contacts/files/2685362/contacts.tar.gz)

### CODE REVIEW

**Comment by phiL0co** [comment]
I have no direct access to my server right now.
This evening, I have no time either.
Will try tomorrow evening!

**Comment by skjnldsv** [comment]
Awesome! Thanks :)

**Comment by phiL0co** [comment]
As I succeeded to make the contacts shown again by editing them on my phone and then syncing them, does it still make sense for me to test this?

I probably won't make out a difference in this case, will I?

**Comment by skjnldsv** [comment]
Probably not yes :)

**Pull request merged**
