### PR TITLE
feat(contacts): implement single column layout

### LINKED ISSUE #3305: Single column layout
### Is your feature request related to a problem? Please describe.

The current layout of Contacts looks misaligned and confusing, and fields jump around the screen on being added.

### Describe the solution you'd like

Single column layout, all the properties are arranged in one column, with another column for the `add new property` button in edit mode and contact quick actions and shared items in view mode.

image
image

Mobile:
image

- [x] Property type (`Home`, `Work`, etc) all have the same width
- [x] Input fields for each property all have the same width 
- [x] All input fields are left aligned
- [ ] Left align name and title + company (Alice Smith, Analyst at Incorporated GmbH) with the text in the left column (Phone, 1234123412, Address, etc)
- [x] Right align icon of each property (phone icon, email icon, etc) with type of property ("Home" in phone, "Home" in email, etc)
- [ ] Having one column only would leave a lot of whitespace on the right of the screen. Here, the "Add new property" button can go. This makes the position consistent no matter how many fields are added. 
- [ ] In view mode the quick actions and shared items could be shown on the right.
- [ ] In mobile view:
  - [ ] Property icon + label, and the meta data (`Home`, `Work`, etc. as well as `Postbox number`, `Street`, etc) is justified left 
  - [ ] Quick actions are shown at the top
  - [ ] Shared items are shown at the bottom 
  - [ ] "Add new property" button is also at the bottom as the last row.

cc @jancborchardt 

### Describe alternatives you've considered

_No response_

### Additional context

part of #1923

### PR DESCRIPTION
**Pull request by st3iny**
Fix #3305 

grafik

## TODO

- [ ] https://github.com/nextcloud/contacts/issues/3325
- [ ] https://github.com/nextcloud/contacts/issues/3326
- [x] More manual testing to ensure that there are no regressions

### CODE REVIEW

**Comment by JohannesGGE** [comment]
If the input on the right is a dropdown, then the delete icon isn't aligned because the dropdown takes more space.

Screenshot from 2023-04-20 15-33-45

**Review by ChristophWurst — COMMENTED** [review]
Works!

On page load I get an error, but it doesn't seem to break the page

```
[Vue warn]: Error in render: "TypeError: this.localContact is undefined"

found in

---> <DetailsHeader> at src/components/DetailsHeader.vue
       <NcAppContentDetails>
         <ContactDetails> at src/components/ContactDetails.vue
           <NcAppContent>
             <ContactsContent> at src/components/AppContent/ContactsContent.vue
               <Content>
                 <Contacts> at src/views/Contacts.vue
                   <ContactsRoot> at src/ContactsRoot.vue
                     <Root>
```

and

```
TypeError: this.localContact is undefined
    excludeFromBirthdayLabel ContactDetails.vue:486
    VueJS 4
    fn ContactDetails.vue:319
    VueJS 2
    render DetailsHeader.vue:49
    node_modules contacts-main.js:41941
vue.runtime.esm.js:1897
```

**Edit**: happen on `main` too. Ignore.

**Comment by st3iny** [comment]
I fixed the issue found by Johannes.

grafik

**Comment by st3iny** [comment]
I rebased and fixed conflicts. The "Add more info" buttons stays below the property list for now. There is another PR to move the buttons around (to the second column if possible).

grafik

**Review by JohannesGGE — APPROVED** [review]

**Pull request merged**
