### PR TITLE
Add favicons

### LINKED ISSUE #1947: Invalid favicon
### Describe the bug
The favicon shown in the browser and the bookmark is the default nextcloud symbol instead of the contacts icon. Other apps (e.g. calendar, mail) show their icon.

**To Reproduce**
* Visit https://domain.tld/apps/contacts
* Observe the favicon in your browser
* Create a bookmark
* Observe the icon of the bookmark

**Expected behavior**
The favicon should not be generic.

**Actual behavior**
The favicon is generic (nextcloud logo).

**Screenshots**
contacts-favicon

### Server configuration

**Web server:** Nginx + php-fpm

**PHP version:** 7.4

**Nextcloud version:** 20.0.2

**Contacts version:** 3.4.2

### Client configuration
**Browser:** Chromium

**Operating system:** Linux

### PR DESCRIPTION
**Pull request by st3iny**
Fixes #1947 

All SVGs were created and converted to PNGs with Inkscape. The ICO version was converted using ImageMagick. For dimensions and styling I adhered to the favicons of nextcloud/mail. 

All PNGs and SVGs were optimized using [nextcloud/server/build/image-optimization.sh](https://github.com/nextcloud/server/blob/master/build/image-optimization.sh).

### CODE REVIEW

**Comment by skjnldsv** [comment]
They're supposed to be generated by the server for quite some times now. Thus why they're not here anymore.
I'm confused to what is happening :thinking: 
cc @juliushaertl, do you know a bit more?

**Comment by st3iny** [comment]
I checked every app on my private instance and I see favicons only for the apps which explicitly ship their own. Could the auto generation be related to the theming app? I had to disable this app because it is not working well when using a s3 bucket as primary storage.

**Comment by juliushaertl** [comment]
It requires imagick with svg support being enabled on the instance, maybe that is not the case here then:

https://github.com/nextcloud/server/blob/cb057829f72c70e819f456edfadbb29d72dba832/apps/theming/lib/Controller/IconController.php#L126
https://github.com/nextcloud/server/blob/f5ef2d7d5897bb490f2a10792760f809a68e4c00/apps/theming/lib/ImageManager.php#L299-L303

**Comment by skjnldsv** [comment]
> It requires imagick with svg support being enabled on the instance, maybe that is not the case here then:

I have imagick enabled and definitely don't have the contacts favicon :thinking: 
I think it's broken?

**Review by skjnldsv — APPROVED** [review]

**Comment by juliushaertl** [comment]
Hm, works for me:
image

**Comment by st3iny** [comment]
@juliushaertl @skjnldsv FYI, the theming app is responsible for automatic thumbnail generation. 

I enabled it on my Nextcloud server and all the favicons are getting generated automatically now. The HTML source code reveals the following url for the generated favicon: `https://nextclouid.tld/apps/theming/favicon/contacts?v=0`.

**Pull request merged**
