### PR TITLE
Allow to input the Date by hand

### PR DESCRIPTION
**Pull request by MrPompom**
Add Parse in dateFormat

fixes https://github.com/nextcloud/contacts/issues/1865

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Do you know if there is a ticket about this?

How do I test this?

**Comment by MrPompom** [comment]
There are a ticket about this : Allow plain-text input for dates #1865

You can test this by create a contact, add a date like birthday and type the date
image

you can type:
oct 11, 2011
october 11, 2011
10/11/2011
10-11-2011

**Comment by JuliaKirschenheuter** [comment]
@MrPompom Thank you for taking over!

Could you please rename your branch, that it would be a bit precisely?

**Review by JuliaKirschenheuter — CHANGES_REQUESTED** [review]
@MrPompom Thank you for taking over!

Could you please rename your branch, that it would be a bit precisely?

Tested - works)

**Pull request merged**
