### PR TITLE
fix the rev test

### PR DESCRIPTION
**Pull request by MrPompom**
Signed-off-by: Bastien PROMPSY <bastienprompsy@gmail.com>

### CODE REVIEW

**Comment by JuliaKirschenheuter** [comment]
@MrPompom could you please elaborate on the problem this fixes? For review and testing I would prefer to have some reproduction steps, either here or in a related bug report. Then we can check main and you branch to see if/how the problem is fixed :)

**Comment by MrPompom** [comment]
This, commit is to correct a warning on the InvalidRev check.

Before this commit, when a contact is selected, a warning invalidateRev appear.

This commit is to stop this invalidateRev warning

**Comment by st3iny** [comment]
I'm not able to reproduce the bug. Could you be a more specific about the steps needed to reproduce the bug?

**Comment by ChristophWurst** [comment]
I'm closing due to lack of feedback from the author.

**Pull request closed without merging**
