### PR TITLE
Fix circle membership request

### LINKED ISSUE #2282: Not-Yet-Members with pending Membership are shown as Member
### Requesting:

- Create a Circle and define it as OPEN, JOINREQUEST
- User wants to join the circle
- User is shown as Member in the members list

### Invitation

- Create a Circle and it as INVITE
- Invite a user
- User is shown as Member in the members list

### LINKED ISSUE #2314: `Request to join` button not present in the main app content
It's present in the navigation, but should also be in the main content list

### LINKED ISSUE #2315: Allow to approve pending request from UI
https://github.com/nextcloud/circles/blob/0c2a162d9900684a5378a08c066737895096c4c0/appinfo/routes.php#L43-L44

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #2282 
Fix #2314 
Fix #2315 

Capture d’écran_2021-07-01_10-32-59

Capture d’écran_2021-06-28_13-26-36

### CODE REVIEW

**Comment by GretaD** [comment]
I am trying to test this pr but i get a lot of errors. Now to make sure Im testing it right, what i am doing is. I add a new user to the circle. The user is added as a member, then i try to demote it to pending, 3 errors are shown: `MembersListItem.vue:287 Could not change the member level to Pending` a `400` and a `404`.

**Comment by skjnldsv** [comment]
> `MembersListItem.vue:287 Could not change the member level to Pending` a `400` and a `404`.

Yes, it's a mistake from my part, sorry!

**Comment by ArtificialOwl** [comment]
is it possible to reject a request from the UI ? while I like the check button, maybe switching to a 3 dot button might be better ?

**Comment by skjnldsv** [comment]
> is it possible to reject a request from the UI ? while I like the check button, maybe switching to a 3 dot button might be better ?

Incoming, I'll push as well, I noticed that was missing today :)

**Comment by skjnldsv** [comment]
@GretaD @ArtificialOwl ready again! Please review and we can release rc1

**Review by GretaD — APPROVED** [review]
All good, apart from when i try to add a circle that has 2 letters, an error is shown. But not sure if its related to this pr directly. Approving so the pr its not blocked if we want to do that in a follow up.

**Comment by GretaD** [comment]
the error that is shown when i add a circle with 2 letters(name)
2charactercicle

**Comment by skjnldsv** [comment]
> the error that is shown when i add a circle with 2 letters(name)

@ArtificialOwl should we expose the limits via capabiliies?

**Pull request merged**
