### PR TITLE
Allow special chars for xing profile image

### PR DESCRIPTION
**Pull request by danopz**
Hi, I just ran into the issue that the social provider for Xing wasn't able to load the profile image of a contact having some german umlauts (äöü) in their name.
After correctly url-encoding them they contain a percentage sign (%) so I just added that to the regex to enable certain special chars.
I also added a test case with some special chars.

### CODE REVIEW

**Review by call-me-matt — APPROVED** [review]
so simple and so effective - thank you!

**Review by skjnldsv — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
Unit tests fail. Please see the action output :)

**Comment by danopz** [comment]
Should be fixed, sad scoping in PHP :smile:

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
CI still says no :zipper_mouth_face:

**Comment by danopz** [comment]
Next try
Sry, don't have a full Nextcloud dev setup so I'm not able to run tests locally

**Pull request merged**
