### PR TITLE
Fix:deselect groups and groups update

### LINKED ISSUE #3516: remove a group from a contact
### Describe the bug

It is not posible to remove a group from a contact. If more than one group in the contact,

### Steps to reproduce

1. Go to any 'contact'
2. Click on 'edit'
3. Click on 'groups'
3. Scroll down to the group you want to remove
4. Nothing happend

### Expected behavior

The Group will remove from the contact.

### Actual behavior

The Group still in the contact.

### Contact version

5.3.2

### Operating system

Ubuntu 22.04

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
fix #3516

### CODE REVIEW

**Review by GretaD — APPROVED** [review]
code looks good

**Review by ChristophWurst — APPROVED** [review]
Tested, works

**Comment by hamza221** [comment]
> Is this PR part of v5.4.1?

@rakekniven  yes

**Comment by hamza221** [comment]
https://github.com/nextcloud/contacts/blob/stable5.4/CHANGELOG.md#541---2023-09-20

**Pull request merged**
