### PR TITLE
adjust the space between avatar and name in the contacts list

### PR DESCRIPTION
**Pull request by xh3n1**
Before:
before
After:
after

### CODE REVIEW

**Comment by skjnldsv** [comment]
This is going into server though. :)

**Comment by irgendwie** [comment]
This leads to the contactList being scroll-able in the horizontal direction (left and right) 🙈
My css pros, how do we fix this? @xh3n1 @skjnldsv @jancborchardt @jonatoni

**Comment by xh3n1** [comment]
@irgendwie I don't think it induces the contactList to being scrollable in the horizontal direction :confused: 
image

**Comment by irgendwie** [comment]
@xh3n1 will recheck

**Comment by irgendwie** [comment]
@xh3n1 It only happens when the scrollbar is visible, meaning you need a bigger number of contacts, then it is scroll-able in the horizontal direction

**Comment by jancborchardt** [comment]
@xh3n1 the element width of the name has to be adjusted. :) Maybe best to do this all in core as @skjnldsv mentioned.

**Comment by irgendwie** [comment]
@xh3n1 Btw, today I found out this problem only occurs in chrome and *not* in firefox - you are using firefox, right?

**Comment by xh3n1** [comment]
@irgendwie I tested it in Firefox and Chromium and this problem does not occur :/

**Comment by irgendwie** [comment]
@jancborchardt @skjnldsv @jonatoni Are also not able to reproduce this issue?

**Pull request merged**
