### PR TITLE
Sharees design fix

### LINKED ISSUE #362: Redesign the sharing tab in settings
This is half broken/half bad designed! :)
We need a better way to display stuff!

I suggest we put the shared with users/groups into a popover! :)

capture d ecran_2017-09-25_18-53-09

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/49713399-redesign-the-sharing-tab-in-settings?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #362

| Before | After |
|:---:|:---:|
| kazam_screenshot_00000 | kazam_screenshot_00001  |

### CODE REVIEW

**Comment by irgendwie** [comment]
fixes #362 

How about some before and after screenshots? :blush:

**Comment by skjnldsv** [comment]
@irgendwie: done! :laughing:

**Comment by jancborchardt** [comment]
Nice! Maybe even a bit more padding for better clickability and vertical whitespace? Otherwise great!

**Comment by irgendwie** [comment]
Looks good, although it seems a bit squished if the translation of 'can edit' is long (like in german)

2017-11-03-140129_257x71

**Comment by skjnldsv** [comment]
> Looks good, although it seems a bit squished if the translation of 'can edit' is long (like in german)

I say, lgtm, it's not that bad! ^^

**Comment by irgendwie** [comment]
@skjnldsv Just wanted to point it out - it's 1000x times better than before ;-)

**Pull request merged**
