### PR TITLE
new contact event fix

### PR DESCRIPTION
**Pull request by AminulBD**
There is typo error for "newContact" event. That has been fixed in this pull request.

### CODE REVIEW

**Comment by miaulalala** [comment]
Hi, thanks for your PR! Could you please add some context? Thanks :smile_cat:

**Comment by AminulBD** [comment]
The component has a button where the event is fired on click. You can [see here](https://github.com/nextcloud/contacts/blob/master/src/components/AppContent/ContactsContent.vue#L34-L36)  But the button is not working when anyone clicked. You know the parent component has the event with `newContact` and this component is firing `new-contact` event which is not correct.

This PR solved the button click problem here.

**Comment by st3iny** [comment]
Events should be named using the kebab case convention. You should change all usages instead of renaming it. AFAIK, this component has only one usage at:
https://github.com/nextcloud/contacts/blob/9ae9b7e463cca26b5842f336d79461a4af87ac99/src/views/Contacts.vue#L47

Please change it there to: `@new-contact="newContact"`

**Comment by miaulalala** [comment]
Hi @AminulBD can you please sign off your commits? You can see here how to do it: https://github.com/nextcloud/contacts/pull/2531/checks?check_run_id=4309770577

**Comment by AminulBD** [comment]
@miaulalala I've done this and pushed again.

**Review by st3iny — APPROVED** [review]

**Pull request merged**
