### PR TITLE
fix submit icon position of the Address book name

### PR DESCRIPTION
**Pull request by xh3n1**
**Before:**

rsz_1before

**After:**

rsz_after

### CODE REVIEW

**Comment by skjnldsv** [comment]
Is the tooltip still correctly positioned?

**Comment by xh3n1** [comment]
Yep :smile: @skjnldsv

**Comment by skjnldsv** [comment]
Strange, the icon isn't wrongly positioned on my side. Which browser are you using?

Anyway, works on my side, but a little bit too much on the left. :)

**Comment by xh3n1** [comment]
I'm using Firefox.

**Comment by skjnldsv** [comment]
@irgendwie I see them correctly aligned in my firefox! :)

**Comment by irgendwie** [comment]
@xh3n1 thanks for the fix! 👍

**Comment by jancborchardt** [comment]
@xh3n1 great fix, thank you! :)

**Pull request merged**
