### PR TITLE
Proper positioning of "Import contacts" and "New contact" buttons

### PR DESCRIPTION
**Pull request by auroraanna**
Continues #3502

### CODE REVIEW

**Comment by auroraanna** [comment]
> > :exclamation: Current head 7beefae differs from pull request most recent head 3288681. Consider uploading reports for the commit 3288681 to get more accurate results

Uh… what? There is only one head and it's
```console
$ git rev-parse --short HEAD
3288681b
```

**Comment by auroraanna** [comment]
Anna doesn't understand why is the code coverage decreased.

**Comment by st3iny** [comment]
Hmm, even rebasing doesn't help. I don't know what is wrong here.

According to githubstatus.com webhooks are broken. Let's see tomorrow.

**Review by st3iny — APPROVED** [review]
Tested and works.

**Pull request merged**
