### PR TITLE
Drone testing

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

### CODE REVIEW

**Comment by Gomez** [comment]
Is drone the way to go? Otherwise i am willing to add Nightly upload to contacts like in Mail & Calendar.

**Comment by skjnldsv** [comment]
It was a pr in progress, but if you have a better way please do! :D 
This is an important task!

**Comment by Gomez** [comment]
I would work on further travis integration. OK?

**Comment by skjnldsv** [comment]
With pleasure :) 
see with @LukasReschke, he's the master of the nextcloud drone 😆

**Pull request closed without merging**
