### PR TITLE
Contacts app is actually in the "Organization" category

### PR DESCRIPTION
**Pull request by LEDfan**
Thanks to Tweakers.net user for reporting.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Actually, it's in three categories: https://github.com/nextcloud/contacts/blob/4c3537983a6dfeb3fcae7546f66c2c56fab6a985/appinfo/info.xml#L17-L19

**Comment by LEDfan** [comment]
I know. For the readme would it be better for to choose one, or list them all?

**Comment by ChristophWurst** [comment]
Yes, that makes sense. Listing all three would be confusing. Nvm my comment then :-)

**Comment by irgendwie** [comment]
Thanks!

**Pull request merged**
