### PR TITLE
Fixes travis integration & adds Nightly builds

### PR DESCRIPTION
**Pull request by Gomez**
This will bring back travis tests and adds nightly uploads. 

@MorrisJobke @LukasReschke Can some1 enable travis for contacts. Thx

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> @MorrisJobke @LukasReschke Can some1 enable travis for contacts. Thx

Done

**Comment by Gomez** [comment]
Travis green again :) @Henni & @irgendwie Can be merged

**Comment by skjnldsv** [comment]
@Gomez you forgot to mention me! :'(

👍 🎉

**Comment by Gomez** [comment]
Sorry was not on purpose. I just noticed, the auto upload don't work. I will check this later

**Pull request merged**
