### PR TITLE
Fix copying text to the clipboard

### LINKED ISSUE #3011: Copying text to the clipboard is broken
### Describe the bug

From @raimund-schluessler second issue here: 

The currently used package vue-clipboard2 has issues with the focus-trap of NcActions and seems anyway deprecated, given there is a native API for copying to the clipboard. This PR fixes the copy function and gets rid of the superfluous package.

See also https://github.com/nextcloud/nextcloud-vue/issues/3275.

### Steps to reproduce

1. Open "Contact settings".
2. Click to action menu of one of the address book.
3. Select "Copy link".

### Expected behavior

Link will be copied 

### Actual behavior

Link is not copied 

### Contact version

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Fixes #3011

Fix copying text to the clipboard by removing `vue-clipboard2`.

Reference https://github.com/nextcloud/tasks/pull/2115

### CODE REVIEW

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
Package lock missing, no?

**Review by ChristophWurst — APPROVED** [review]

**Review by st3iny — CHANGES_REQUESTED** [review]
Lock is incomplete

**Review by st3iny — APPROVED** [review]
I fixed the lock and eslint issues.

**Pull request merged**
