### PR TITLE
trigger re-index and optimize query by social field

### PR DESCRIPTION
**Pull request by call-me-matt**
trigger re-index of contacts to optimize query in background updates

### CODE REVIEW

**Comment by call-me-matt** [comment]
This is a follow-up of https://github.com/nextcloud/server/pull/22085

**Comment by skjnldsv** [comment]
Im' wondering if this should really be a cron job. Shouldn't it be a migration instead? @rullzer @nickvergessen @georgehrke  ?

**Comment by nickvergessen** [comment]
It's a repair step, exactly what it should be, but it's not registered in info.xml

**Comment by skjnldsv** [comment]
> Im' wondering if this should really be a cron job. Shouldn't it be a migration instead? @rullzer @nickvergessen @georgehrke ?

AH, I misread the code!
My bad :)

**Comment by call-me-matt** [comment]
Thank you for your feedback, I will move the code to the server then (and pack it into background-chunks)

**Pull request closed without merging**
