### PR TITLE
Url decode groups and users

### LINKED ISSUE #873: Unable to share addressbooks with groups having space in name
### Describe the bug
It's impossible to share addressbooks with NextCloud groups that have a space in their name.

**To Reproduce**
1. Create a group in NextCloud settings with a name that contains a space
2. Create a new address book in the contacts app
3. Click the share button of your new address book
4. Enter part of the name of the group you just created
5. The dropdown should render the name of the group with %20 (for example `Testie%20Testie`)
6. Click the group to share the addressbook: the group is added to the book in the UI
7. Refresh the page
8. Check if the group is still in the share UI for the addressbook: it's gone.

**Expected behavior**
Sharing addressbooks with groups that have spaces in names

**Actual behavior**
Unable to share addressbooks with groups that have spaces in names

**Screenshots**
screenshot 2019-01-19 at 21 17 10

### Server configuration
We're using Docker to run Nextcloud on Linux, using nginx. Basic docker-compose with the latest `nextcloud:15-fpm` and `postgres:10.5`.

**Operating system**: Linux
**Web server:** nginx
**Database:** PostgreSQL
**PHP version:** 7.2-fpm
**Nextcloud version:** 15.0.2
**Contacts version:** 3.0.1
**Updated from an older Nextcloud or fresh install:** Updated from 15.0.2

**Signing status:**
/settings/integrity/failed outputs `No errors have been found.`

**List of activated apps:**
Accessibility
Activity
Auditing / Logging
Calendar
Collaborative tags
Comments
Concrexit Auth
Contacts
Deck
Deleted files
File sharing
First run wizard
Gallery
Group folders
Log Reader
Markdown Editor
Monitoring
Notifications
Notifications for calendar event updates
PDF viewer
Share by mail
Support
Tasks
Text editor
Theming
Two Factor TOTP Provider
Update notification
Versions
Video player

**Nextcloud configuration:**
Only security settings that are not relevant to this app afaik.

### Client configuration
**Browser:** Firefox and Chrome
**Operating system:** macOS
**CardDAV-clients:** NextCloud UI

#### *Web server error log*
No errors in nginx. The response is a 200.

#### *data/nextcloud.log*
Nothing to report about this app.

#### 'Browser log'
I've taken the time to analyse the calls to the dav endpoint made by the contacts app. I wanted to compare them with the calendar app and see what the difference was.

This is a share call from the contacts app:
```
POST https://{url}/remote.php/dav/addressbooks/users/{user}/testie-test/
<x4:share xmlns:x4="http://owncloud.org/ns">
    <x4:set>
        <x0:href xmlns:x0="DAV:">principal:principals/groups/Testie%20Test</x0:href>
    </x4:set>
</x4:share>
RESPONSE: OK 200
```

This is a share call from the calendar app:
```
POST https://{url}/remote.php/dav/calendars/{user}/testie-test/
<o:share xmlns:o="http://owncloud.org/ns">
    <o:set>
        <d:href xmlns:d="DAV:">principal:principals/groups/Testie Test</d:href>
        <o:summary>Testie Test shared by {user}</o:summary>
    </o:set>
</o:share>
RESPONSE: OK 200
```

Notice the difference in the principal url the apps use. Contacts url-encodes the space in the principal url, calendar does not. So I guess the url shouldn't be encoded, but what do I know. I've only been looking into this for the past 2 hours. So I decided it was better to just open an issue and see what anyone else thinks.

Quick edit: looks like manually sending the share requests without the url encoded principal makes the addressbooks shared as I would expect them to be. Also looks like the url encoding breaks names with `"` and `+` in them as well.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/68925973-unable-to-share-addressbooks-with-groups-having-space-in-name?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751899&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #873 

@se-bastiaan

### CODE REVIEW

**Comment by georgehrke** [comment]
not sure whether we should decode it here or in the dav lib. will check.

**Comment by skjnldsv** [comment]
@georgehrke bump ;)

**Comment by georgehrke** [comment]
Tonight

**Comment by skjnldsv** [comment]
Meging for the release. We'll see for another fix later ;)

**Pull request merged**
