### PR TITLE
Downgrade to Vue 2.6

### PR DESCRIPTION
**Pull request by ChristophWurst**
The virtual scroller isn't ready for 2.7 yet.

### CODE REVIEW

**Review by miaulalala — APPROVED** [review]

**Review by st3iny — APPROVED** [review]
Tested and works. The contact list renders again.

One issue: The contact view (rightmost panel) is not scrollable. However, this is also the case on main before the initial vue bump.

**Comment by ChristophWurst** [comment]
> One issue: The contact view (rightmost panel) is not scrollable. However, this is also the case on main before the initial vue bump.

That is the incompatibility of the new container layout and the lack of nc/vue7

**Comment by ChristophWurst** [comment]
@st3iny can you reproduce the failing esling/build locally? It works on my machine

**Comment by st3iny** [comment]
> @st3iny can you reproduce the failing esling/build locally? It works on my machine

Works on my machine too. Even with the same node and npm versions.

**Comment by ChristophWurst** [comment]
@GretaD could you try as well please?

**Comment by ChristophWurst** [comment]
Deps are a bit of a mess now ngl

**Review by GretaD — APPROVED** [review]
i can see my contancts list while on this pr and no errors on my console

**Pull request merged**
