### PR TITLE
Implement Drag and Drop feature for adding contacts to group

### PR DESCRIPTION
**Pull request by SteKoe**
This PR implements the requested feature in #564. I have also added some Docker-related files to allow running the app in a dockerized Nextcloud instance. I have added a section to the README.md file :)

https://user-images.githubusercontent.com/1809221/136859286-a73d3665-2b8c-48b1-bb09-e6aaee02db91.mp4

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Awesome feature!

We'll review this soon.

Regarding the Dockerized dev setup, I would prefer to not have this in the app repo. After all there are hundres of Nextcloud apps and we can't maintain dev setup instructions and configuration everywhere. Are your instructions something that we could integrate into https://docs.nextcloud.com/server/stable/developer_manual/getting_started/devenv.html?

**Comment by szaimen** [comment]
I just rebased this. Hopefully I didn't break anything while doing so.

**Comment by ChristophWurst** [comment]
Almost

Bildschirmfoto vom 2022-10-17 19-56-10

**Comment by ChristophWurst** [comment]
Hey @SteKoe!

Friendly ping on the requested changes above. Do you have the time needed to finish and get into a mereable state?

Cheers

**Comment by hamza221** [comment]
Rebased and Updated the Pr

**Review by miaulalala — CHANGES_REQUESTED** [review]
~~This does nothing for me - I can't drag & drop the contact to any contact group~~ nvm browser cache

**Comment by hamza221** [comment]
> This does nothing for me - I can't drag & drop the contact to any contact group
for all contacts? because it doesn't work for SAB contacts by design

**Review by miaulalala — APPROVED** [review]
Only thing that I don't like but it's not a big problem is that the Contacts group changes to a disabled input field instead of updating the text. Otoh it provides a nice visual feedback that the groups have changed so that's just me being prissy:

image

**Comment by hamza221** [comment]
> Only thing that I don't like but it's not a big problem is that the Contacts group changes to a disabled input field instead of updating the text. Otoh it provides a nice visual feedback that the groups have changed so that's just me being prissy:
> 
> image


https://github.com/nextcloud/contacts/pull/3752 there's a PR to fix that already maybe it's time to get it merged

**Review by ChristophWurst — APPROVED** [review]
Looks good as https://github.com/nextcloud/contacts/pull/2466/files?w=1

**Pull request merged**
