### PR TITLE
Disable autocorrection

### PR DESCRIPTION
**Pull request by skjnldsv**
No more this!
capture d ecran_2016-11-25_16-07-38

### CODE REVIEW

**Comment by MariusBluem** [comment]
I agree with that 👍

**Comment by irgendwie** [comment]
This would leave auto-correction for 'detailed name' and various other fields
and only affect the contact header, correct?
Do we really want to disable this "feature"? What is the common practice for this?
cc @jancborchardt

**Comment by skjnldsv** [comment]
Yes, this is correct. Maybe we should indeed extend it to more values. Like phones, detailed names (which I forgot we had ^^)...

**Comment by irgendwie** [comment]
@skjnldsv It seems logical for me to expand the disabled auto-correct to detailed name but not more fields. Which means name and organization in the header and detailed name in the details view. Should be enough for now - would you mind making the required changes?

**Comment by skjnldsv** [comment]
Your wish is my command! 🚀

**Comment by irgendwie** [comment]
LGTM :+1:

**Comment by jancborchardt** [comment]
Good detail fix @skjnldsv! :+1:

**Pull request merged**
