### PR TITLE
Fit contacts list to guidelines

### LINKED ISSUE #448: Navigation toggle and back button not shown on mobile anymore
Previously we had the hamburger menu button on the top left so you can toggle the sidebar. And when the contact detail view is open, we had a back button. This is not there anymore, maybe due to some JS change? Because we insert `app-navigation-toggle` into `app-content`.

cc @nextcloud/contacts @nextcloud/javascript

### PR DESCRIPTION
**Pull request by skjnldsv**
After https://github.com/nextcloud/server/pull/7195
Fix  #448

### CODE REVIEW

**Comment by irgendwie** [comment]
Compatible with at least Nextcloud 12?

**Comment by skjnldsv** [comment]
@irgendwie No, patch for 12 will come in next pr :)

**Comment by skjnldsv** [comment]
Can we please get this in?

**Comment by irgendwie** [comment]
2017-12-07-172354_1137x293_scrot

- Scrolling in the contacts list completely broken for me
- White space on the right next to the delete icon

Only for me?

**Comment by skjnldsv** [comment]
@irgendwie nope, here as well, this is due to server, I have a patch coming asap. Don't know how I missed it....

**Comment by skjnldsv** [comment]
Rebased for merging

**Comment by skjnldsv** [comment]
> When reducing the width, shortly before it breaks to mobile view, there’s a horizontal scrollbar.
> When the width is reduced and you click on a contact, the app-content-list briefly expands width while loading the new contact.

Can't reproduce, still happening with latest commits from https://github.com/nextcloud/server/pull/7195 ?

**Comment by jancborchardt** [comment]
Two more strange issues:
In Firefox, for entries with only a name the avatar sometimes glitches to the top (sometimes only when zooming, sometimes jitters a bit when loading the app):
screenshot from 2017-12-12 14-29-28

In Chrome, the app-content-list is strangely narrow for contacts which have 2 columns (censored the contact names but it’s still very narrow, see the scrollbar/divider):
screenshot from 2017-12-12 14-32-02

**Comment by skjnldsv** [comment]
@jancborchardt this is related to the column system! :/

**Comment by jancborchardt** [comment]
@skjnldsv yeah, thought so :/

@nextcloud/contacts what do you think - let's get this in for 13 and fix going forward?

**Comment by skjnldsv** [comment]
@jancborchardt can you update your review? :)

**Pull request merged**
